@extends('layouts.eiaaw')

@section('title', 'EIAAW Social Media Team — AI that shows you the receipts')
@section('description', 'Stop paying for AI that hallucinates your brand voice. EIAAW Social Media Team is the only autonomous AI social system that grounds every caption, every image, every recommendation in your real brand evidence — and shows you the source. Built for SMBs and agencies across Malaysia and APAC.')

@section('content')

{{-- ───────────────────────── HERO ───────────────────────── --}}
<section class="section-pad" style="padding-top: clamp(140px, 18vh, 220px);">
  <div class="wrap">
    <div class="grid-12" style="align-items: end;">
      <div style="grid-column: 1 / span 7;">
        <span class="eyebrow rvl">EIAAW Social Media Team &middot; v1 launching now</span>
        <h1 class="display rvl kinetic" style="margin-top: 28px;">
          <span class="word">Stop</span>
          <span class="word">paying</span>
          <span class="word">for</span>
          <span class="word">AI</span>
          <span class="word">that</span>
          <span class="word">hallucinates</span>
          <span class="word"><em>your brand.</em></span>
        </h1>
        <p class="lead rvl" style="margin-top: 36px;">
          Every other tool in the category ships a generic caption, a hit-or-miss prediction, or an off-brand image — then bills you to regenerate it. EIAAW Social Media Team is built differently. <strong>Every post comes with receipts</strong>: which brand evidence grounded each phrase, which prior post the angle was modelled on, which compliance check it passed, what it cost to produce.
        </p>
        <div class="rvl" style="margin-top: 44px; display: flex; gap: 18px; flex-wrap: wrap;">
          <a href="{{ url('/signup') }}" class="btn btn-primary btn-lg">Subscribe now <span class="arrow">&rarr;</span></a>
          <a href="#how" class="btn btn-ghost btn-lg">See how it works</a>
        </div>
        <div class="rvl" style="margin-top: 28px; font-family: var(--mono); font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--mute);">
          Flat brand-based pricing &middot; no per-user tax &middot; no per-channel fees &middot; Malaysia-only in v1
        </div>
      </div>
      <div style="grid-column: 8 / span 5; padding-top: 60px;" class="elegant-figure-parent">
        <div class="rvl elegant-figure receipt-card">
          <div class="receipt-card-inner">
            <div class="eyebrow" style="margin-bottom: 18px;">A real receipt</div>
            <p style="font-family: var(--serif); font-style: italic; font-size: 22px; line-height: 1.35; color: var(--ink);">
              "Most agencies are <em>quietly</em> using AI but won't admit it because the output is generic."
            </p>
            <div style="margin-top: 22px; padding-top: 22px; border-top: 1px dashed var(--line); font-size: 13px; color: var(--ink-2); line-height: 1.6;">
              <div><strong>Grounded in:</strong> Acme Studio's <span style="color: var(--primary-dark); border-bottom: 1px dotted var(--primary-dark); cursor: help;">2025 Q4 manifesto post</span> &middot; engagement 4.2&times; baseline</div>
              <div style="margin-top: 6px;"><strong>Brand voice score:</strong> 0.91 / 0.85 threshold &middot; <strong>Compliance:</strong> 5 / 5 passed</div>
              <div style="margin-top: 6px;"><strong>Generated by:</strong> Writer &middot; claude-sonnet-4-6 &middot; 0.041 USD</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{{-- ───────────────────────── THE PROBLEM ───────────────────────── --}}
<section class="section-pad" style="background: var(--bg-warm); border-top: 1px solid var(--line-soft); border-bottom: 1px solid var(--line-soft);">
  <div class="wrap">
    <div class="section-head">
      <div class="label"><span class="eyebrow">01 / The category is broken</span></div>
      <h2 class="title section-h">
        Every existing AI social tool fails in the <em>same five ways.</em>
      </h2>
      <div class="aside">Audited 30+ tools, April 2026</div>
    </div>

    <div class="grid-12" style="row-gap: 48px;">
      @php
        $failures = [
          [
            'n' => '01',
            'title' => 'Captions need 5–10 minutes of human rewrite per post.',
            'detail' => 'Buffer, Hootsuite, Later, Predis, Ocoya, Publer, Jasper, Copy.ai, Simplified, Taplio, Postwise — independent reviews uniformly say the AI ships generic first drafts. The human still does the work.',
          ],
          [
            'n' => '02',
            'title' => 'Performance predictions are made up.',
            'detail' => 'FeedHive ships a viral score with no source. Predis offers competitor analysis with documented bugs. Nobody shows you the comparable historical posts behind the prediction — because there are none.',
          ],
          [
            'n' => '03',
            'title' => '"Brand voice training" is theatre.',
            'detail' => 'Lately, Jasper, Taplio, Postwise all claim brand voice training. Most train on a URL or a short description — not your actual high-performing post corpus. Output reads formulaic.',
          ],
          [
            'n' => '04',
            'title' => 'AI fabricates citations and facts.',
            'detail' => 'Copy.ai is on record fabricating references. Make-driven workflows warn users to "double-check captions for accuracy." Simplified produces non-prompt-adherent output. None ship a confidence score.',
          ],
          [
            'n' => '05',
            'title' => 'Per-user pricing punishes growth. Per-channel fees pile up.',
            'detail' => 'Hootsuite $199/user. Sprout $199/user. Buffer charges per channel. A 10-person agency pays $24K–$48K/year — for AI everyone says still misses. We price flat per brand, no per-seat or per-channel tax.',
          ],
          [
            'n' => '06',
            'title' => 'Cancellation is a trust trap.',
            'detail' => 'Jasper Trustpilot reports $500+ post-cancel charges. AdCreative scores 3.6 / 5 on Trustpilot. Magai users report ignored refunds. Loomly sits at 1.7 / 5. The category has burned its credibility.',
          ],
        ];
      @endphp
      @foreach ($failures as $i => $f)
        <article class="rvl" style="grid-column: span {{ $i % 3 === 1 ? 4 : 4 }};">
          <div class="eyebrow" style="margin-bottom: 14px;">{{ $f['n'] }}</div>
          <h3 style="font-family: var(--sans); font-weight: 500; font-size: clamp(20px, 1.6vw, 26px); line-height: 1.2; letter-spacing: -0.02em; color: var(--ink); max-width: 24ch;">{{ $f['title'] }}</h3>
          <p style="margin-top: 14px; color: var(--ink-2); line-height: 1.55; font-size: 15px;">{{ $f['detail'] }}</p>
        </article>
      @endforeach
    </div>
  </div>
</section>

{{-- ───────────────────────── HOW IT WORKS ───────────────────────── --}}
<section id="how" class="section-pad">
  <div class="wrap">
    <div class="section-head">
      <div class="label"><span class="eyebrow">02 / How EIAAW is different</span></div>
      <h2 class="title section-h">
        Six specialised agents. <em>One hard compliance gate.</em>
      </h2>
      <div class="aside">Architecture, not vibes</div>
    </div>

    <div class="grid-12">
      <div style="grid-column: 1 / span 5;">
        <p class="lead">
          Most "AI social media teams" are one LLM with role prompts pretending to be six. EIAAW's agents are genuinely separate — different memory, different tool scopes, different evals between each handoff.
        </p>
        <p style="margin-top: 24px; color: var(--ink-2); line-height: 1.65;">
          Every Writer, Designer, and Video output flows through the Compliance agent before anything reaches you. If the brand-voice score, factual grounding, embargo check, prior-post deduplication, banned phrase, learned-rule, or platform-publishability check fails — the post is <strong>held with the reason shown</strong>. Seven checks per post. No silent hallucinations. No off-brand visuals slipping through.
        </p>
      </div>

      <div id="agents" style="grid-column: 7 / span 6; display: grid; grid-template-columns: 1fr 1fr; gap: 18px;">
        @php
          // These are the 6 agents on the active publishing path. The
          // platform also ships Researcher, Optimizer, Repurpose, Onboarding,
          // CompetitorIntel + the Scheduler — surfaced inside the product,
          // not on the marketing page (keeps the message focused on the
          // publishing loop the customer cares about). Compliance is the
          // hard gate that runs 7 checks (see ComplianceAgent::handle).
          $agents = [
            ['Strategist', 'Builds the monthly calendar from your brand evidence + historical performance.'],
            ['Researcher', 'Pulls competitor + market signal into the brief so the Writer isn\'t guessing.'],
            ['Writer', 'Drafts captions grounded in your real high-performing posts, with citation chips on every phrase.'],
            ['Designer', 'Generates on-brand stills via FAL.AI Nano Banana (Gemini 2.5 Flash Image) — locked to your palette, typography, logo placement.'],
            ['Video', 'Generates short-form video via FAL.AI Google Veo 3 (Reels / TikTok / Shorts), narrated from the scripted caption with native synced audio.'],
            ['Compliance', 'The hard gate. Seven checks per post (platform-publishability, learned-rules, banned-phrases, embargo, dedup, brand-voice, factual-grounding). Fail = held.'],
          ];
        @endphp
        @foreach ($agents as $i => [$name, $desc])
          <div class="rvl" style="border: 1px solid var(--line); border-radius: 14px; padding: 22px; background: var(--surface); {{ $name === 'Compliance' ? 'border-color: var(--ink); background: var(--ink); color: var(--bg);' : '' }}">
            <div class="eyebrow" style="margin-bottom: 12px; {{ $name === 'Compliance' ? 'color: var(--bg);' : '' }}">{{ str_pad($i+1, 2, '0', STR_PAD_LEFT) }}</div>
            <strong style="font-size: 16px; letter-spacing: -0.01em; {{ $name === 'Compliance' ? 'color: var(--bg);' : 'color: var(--ink);' }}">{{ $name }}</strong>
            <p style="margin-top: 8px; font-size: 13px; line-height: 1.55; {{ $name === 'Compliance' ? 'color: rgba(250,247,242,0.8);' : 'color: var(--ink-2);' }}">{{ $desc }}</p>
          </div>
        @endforeach
      </div>
    </div>

    <p class="rvl" style="margin-top: 32px; font-family: var(--mono); font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--mute); text-align: center;">
      Plus a Scheduler that ships via Blotato, an Optimizer that retunes weekly from real engagement, a Repurpose agent that recycles winners across platforms, and a Competitor-intel agent that refreshes Mondays
    </p>
  </div>
</section>

{{-- ───────────────────────── RECEIPTS ───────────────────────── --}}
<section id="receipts" class="section-pad" style="background: var(--ink); color: var(--bg);">
  <div class="wrap">
    <div class="section-head">
      <div class="label"><span class="eyebrow" style="color: var(--primary);">03 / Receipts on every post</span></div>
      <h2 class="title section-h" style="color: var(--bg);">
        The provenance layer <em style="color: var(--primary);">nobody else ships.</em>
      </h2>
      <div class="aside" style="color: rgba(250,247,242,0.5);">Click any phrase to see the source</div>
    </div>

    <div class="grid-12" style="row-gap: 36px;">
      @php
        $receipts = [
          [
            'h' => 'Caption receipts',
            'b' => 'Each phrase shows which brand-style.md section grounded it, which prior high-performing post the angle was modelled on (with date and actual metrics), which competitor reference was studied. No more "trust the AI."',
          ],
          [
            'h' => 'Image &amp; video receipts',
            'b' => 'Prompt used, model + version (Nano Banana for stills, Google Veo 3 Fast for video), source assets composited, brand-DNA pass/fail per token (palette, typography, logo placement). Every image and clip carries an explicit AI-generated flag — honest disclosure ready for Meta, TikTok, and YouTube\'s synthetic-media policies.',
          ],
          [
            'h' => 'Recommendation receipts',
            'b' => '"Post Tuesday 9am" shows the historical posts that informed it (sample size, dates, actual engagement), confidence interval, and a warning if N &lt; 30. We refuse to invent numbers.',
          ],
          [
            'h' => 'Failure-mode telemetry',
            'b' => 'A weekly dashboard tells you: 14 posts held this week. 6 brand-voice fails. 5 unverified factual claims. 3 embargo hits. Click each one for the held draft and the reason. SREs don\'t hide failures. We don\'t either.',
          ],
        ];
      @endphp
      @foreach ($receipts as $r)
        <div class="rvl" style="grid-column: span 6;">
          <h3 style="font-family: var(--sans); font-weight: 500; font-size: clamp(22px, 1.8vw, 30px); line-height: 1.2; letter-spacing: -0.02em; color: var(--bg); max-width: 18ch;">{{ $r['h'] }}</h3>
          <p style="margin-top: 14px; color: rgba(250,247,242,0.78); line-height: 1.65; max-width: 52ch;">{!! $r['b'] !!}</p>
        </div>
      @endforeach
    </div>
  </div>
</section>

{{-- ───────────────────────── TIERED AUTONOMY ───────────────────────── --}}
<section class="section-pad">
  <div class="wrap">
    <div class="section-head">
      <div class="label"><span class="eyebrow">04 / Tiered autonomy</span></div>
      <h2 class="title section-h">
        You decide what runs <em>without you.</em>
      </h2>
      <div class="aside">Configurable per brand, per platform, per topic</div>
    </div>

    <div class="grid-12" style="gap: 24px;">
      @php
        // Production ships two lanes (the Red two-human lane was retired in
        // 9f8611b → see AutonomyLane.php). Compliance is the real hard gate
        // — anything held there blocks all lanes equally. Single-approval
        // is enough at the autonomy layer because Compliance is what stops
        // off-brand or non-compliant content from reaching the queue in
        // the first place.
        $lanes = [
          ['name' => 'Green lane', 'color' => 'var(--primary)', 'rule' => 'Auto-publish if Compliance passes.', 'use' => 'Evergreen tips, recurring formats, brand-value content. Runs while you sleep — every post still passes the 7-check Compliance gate first.'],
          ['name' => 'Amber lane', 'color' => 'var(--ink)', 'rule' => 'Single human approval required.', 'use' => 'Product claims, news-cycle adjacent posts, anything matching your flagged keywords. Default for new brands and client accounts.'],
        ];
      @endphp
      @foreach ($lanes as $l)
        <div class="rvl" style="grid-column: span 6; border-top: 4px solid {{ $l['color'] }}; padding-top: 24px;">
          <strong style="font-family: var(--sans); font-size: 22px; letter-spacing: -0.015em; color: var(--ink);">{{ $l['name'] }}</strong>
          <div style="margin-top: 8px; font-family: var(--mono); font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; color: {{ $l['color'] }};">{{ $l['rule'] }}</div>
          <p style="margin-top: 16px; color: var(--ink-2); line-height: 1.6; font-size: 15px;">{{ $l['use'] }}</p>
        </div>
      @endforeach
    </div>

    <p class="rvl" style="margin-top: 32px; font-family: var(--mono); font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--mute); text-align: center;">
      Need crisis-window lockdown? Pause publishing per workspace with one toggle &middot; resumes when you say so
    </p>
  </div>
</section>

{{-- ───────────────────────── PRICING ───────────────────────── --}}
<section id="pricing" class="section-pad" style="background: var(--bg-warm); border-top: 1px solid var(--line-soft);">
  <div class="wrap">
    <div class="section-head">
      <div class="label"><span class="eyebrow">05 / Pricing</span></div>
      <h2 class="title section-h">
        Flat. Brand-based. <em>No per-user tax.</em>
      </h2>
      <div class="aside">Cancel any time. No auto-renewal trap.</div>
    </div>

    <div class="grid-12" style="gap: 24px;">
      {{-- Pricing is derived from config/billing.php via
           SignupController::tiersFromConfig() so the landing page and
           /signup picker can NEVER drift. Edit prices in config, not here. --}}
      @php $tiers = \App\Http\Controllers\SignupController::tiersFromConfig(); @endphp
      @foreach ($tiers as $t)
        <div class="rvl" style="grid-column: span 3; padding: 32px; border-radius: 16px; background: var(--surface); border: 1px solid var(--line); {{ ($t['highlight'] ?? false) ? 'border: 2px solid var(--ink); transform: translateY(-12px);' : '' }}">
          <strong style="font-family: var(--sans); font-size: 22px; letter-spacing: -0.015em; color: var(--ink);">{{ $t['name'] }}</strong>
          <div style="margin-top: 18px; display: flex; align-items: baseline; gap: 6px;">
            <span style="font-family: var(--sans); font-weight: 500; font-size: {{ ($t['is_contact'] ?? false) ? '44px' : '52px' }}; letter-spacing: -0.04em; color: var(--ink);">{{ $t['price'] }}</span>
            @if ($t['unit'] !== '')
            <span style="font-size: 14px; color: var(--mute);">{{ $t['unit'] }}</span>
            @endif
          </div>
          @if (! ($t['is_contact'] ?? false))
          <div style="margin-top: 6px; font-size: 12px; color: var(--mute); font-family: var(--mono);">
            or RM {{ number_format($t['annual_myr']) }}/year &middot; save RM {{ number_format($t['annual_savings_myr']) }} (2 months free)
          </div>
          @else
          <div style="margin-top: 6px; font-size: 12px; color: var(--mute); font-family: var(--mono);">
            bespoke pricing &middot; scoped to your operation
          </div>
          @endif
          <ul style="margin-top: 24px; list-style: none; padding: 0; display: flex; flex-direction: column; gap: 10px;">
            <li style="display: flex; align-items: center; gap: 10px; font-size: 14px; color: var(--ink-2);"><span style="width: 4px; height: 4px; border-radius: 50%; background: var(--primary);"></span>{{ $t['brands'] }}</li>
            <li style="display: flex; align-items: center; gap: 10px; font-size: 14px; color: var(--ink-2);"><span style="width: 4px; height: 4px; border-radius: 50%; background: var(--primary);"></span>{{ $t['posts'] }}</li>
            <li style="display: flex; align-items: center; gap: 10px; font-size: 14px; color: var(--ink-2);"><span style="width: 4px; height: 4px; border-radius: 50%; background: var(--primary);"></span>{{ $t['videos'] }}</li>
            @if (! empty($t['platforms_label']))
            <li style="display: flex; align-items: center; gap: 10px; font-size: 14px; color: var(--ink-2);"><span style="width: 4px; height: 4px; border-radius: 50%; background: var(--primary);"></span>{{ $t['platforms_label'] }}</li>
            @endif
            <li style="display: flex; align-items: center; gap: 10px; font-size: 14px; color: var(--ink-2);"><span style="width: 4px; height: 4px; border-radius: 50%; background: var(--primary);"></span>All 6 agents + full receipts</li>
            <li style="display: flex; align-items: center; gap: 10px; font-size: 14px; color: var(--ink-2);"><span style="width: 4px; height: 4px; border-radius: 50%; background: var(--primary);"></span>Tiered autonomy (green/amber)</li>
          </ul>
          <p style="margin-top: 20px; font-size: 13px; color: var(--ink-2); line-height: 1.5; font-style: italic;">{{ $t['best'] }}</p>
          <a href="{{ $t['cta_url'] }}" class="btn {{ ($t['highlight'] ?? false) ? 'btn-primary' : 'btn-outline' }}" style="margin-top: 24px; width: 100%; justify-content: center;">{{ $t['cta_label'] }} <span class="arrow">&rarr;</span></a>
        </div>
      @endforeach
    </div>

    <p class="rvl" style="margin-top: 48px; font-family: var(--mono); font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--mute); text-align: center;">
      Prices exclusive of any applicable taxes &middot; Malaysia-only in v1 &middot; cancel any time &middot; card billing via Stripe (FPX via Billplz coming)
    </p>
  </div>
</section>

{{-- ───────────────────────── CTA ───────────────────────── --}}
<section class="section-pad" style="text-align: left;">
  <div class="wrap">
    <div class="grid-12" style="align-items: end;">
      <div style="grid-column: 1 / span 8;">
        <h2 class="section-h rvl">
          Built by EIAAW Solutions <em>in Malaysia</em>, for SMBs who refuse to settle for AI slop.
        </h2>
        <p class="lead rvl" style="margin-top: 28px;">
          We run this on our own brands first — EIAAW Workforce, Sales Marketing Agent, EIAAW AI ADS Agency, Claritas, SAINS CRM. If it doesn't deliver real results we measure ourselves, we don't ship it to you.
        </p>
        <div class="rvl" style="margin-top: 36px; display: flex; gap: 18px; flex-wrap: wrap;">
          <a href="{{ url('/signup') }}" class="btn btn-primary btn-lg">Start your subscription <span class="arrow">&rarr;</span></a>
          <a href="#" data-smt="contact" class="btn btn-ghost btn-lg">Talk to us</a>
        </div>
      </div>
    </div>
  </div>
</section>

@endsection

@push('scripts')
  {{-- Floating support chatbot — landing surface (sale-conversion mode). --}}
  @include('partials.smt-chat-widget', ['surface' => 'landing'])
@endpush
