<?php

namespace App\Services\Imagery;

use App\Exceptions\AlreadyScheduledException;
use App\Models\Brand;
use App\Models\BrandAsset;
use App\Models\CalendarEntry;
use App\Models\ContentCalendar;
use App\Models\Draft;
use App\Services\Readiness\SetupReadiness;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Turns one customised-intent BrandAsset + a narrative + target platforms +
 * a publish datetime into scheduled posts — WITHOUT inventing a parallel
 * publishing rail.
 *
 * It produces the exact same artefacts the autonomous pipeline produces:
 *   - a "Customised posts" ContentCalendar (one per brand, reused)
 *   - one CalendarEntry per submission, carrying the chosen date/time (so the
 *     existing posts:auto-schedule-approved resolves scheduled_for in the
 *     brand's timezone from scheduled_date + scheduled_time, unchanged)
 *   - one Draft per target platform, with:
 *       * body = the operator's (or AI-written, already-reviewed) narrative
 *       * asset_url pre-attached from the BrandAsset (Blotato re-host happens
 *         here, mirroring DesignerAgent's library-pick path)
 *       * status = 'compliance_pending' — then we run the SAME 7-check
 *         ComplianceAgent as the autonomous pipeline (after the write
 *         transaction commits). The brand lane decides the landing state:
 *         green → 'approved' (auto-queues), amber/red → 'awaiting_approval'
 *         (waits for the operator on the Drafts page).
 *
 * The downstream chain is untouched:
 *   posts:auto-schedule-approved → ScheduledPost(queued)
 *   posts:dispatch-due           → SubmitScheduledPost → Metricool
 *
 * Compliance runs, but operator copy is NEVER auto-rewritten. The agent-side
 * auto-redraft loop (drafts:redraft-failed → RedraftFailedDraft) explicitly
 * skips operator-authored drafts (agent_role='operator' /
 * prompt_version='customised-post.v1'), so a flagged customised post surfaces
 * for manual review/edit instead of being silently regenerated by the Writer.
 * The publish-time PlatformRules gate in SubmitScheduledPost remains the final
 * safety net for caption/media validity.
 */
class CustomisedPostScheduler
{
    /** Platforms the customised flow can target (subset of WriterPrompt limits). */
    public const SUPPORTED_PLATFORMS = [
        'instagram', 'facebook', 'linkedin', 'tiktok',
        'threads', 'x', 'youtube', 'pinterest',
    ];

    public function __construct(
        private readonly BlotatoRehost $rehost,
    ) {}

    /**
     * @param  array<int,string>  $platforms  target platform enums
     * @return array{calendar_entry: CalendarEntry, drafts: array<int,Draft>, asset: BrandAsset}
     */
    public function schedule(
        BrandAsset $asset,
        Brand $brand,
        string $narrative,
        array $platforms,
        Carbon $publishAt,
        string $narrativeSource = 'manual',
        ?array $hashtags = null,
    ): array {
        $platforms = self::normalisePlatforms($platforms);
        if (empty($platforms)) {
            throw new \InvalidArgumentException('Pick at least one supported platform.');
        }
        $narrative = trim($narrative);
        if ($narrative === '') {
            throw new \InvalidArgumentException('A post narrative is required.');
        }
        if ($asset->brand_id !== $brand->id) {
            // Tenant-safety: never let an asset from another brand be scheduled here.
            throw new \InvalidArgumentException('Asset does not belong to this brand.');
        }

        // Re-host the asset on THIS workspace's Blotato account once, up-front,
        // so every per-platform draft shares the same Blotato-scoped media URL.
        // Soft-fail to the raw public_url — SubmitScheduledPost re-uploads media
        // at publish time anyway, so a failure here is not fatal.
        $assetUrl = $this->rehost->forBrand($brand, $asset->public_url) ?? $asset->public_url;

        $result = DB::transaction(function () use (
            $asset, $brand, $narrative, $platforms, $publishAt, $narrativeSource, $hashtags, $assetUrl
        ): array {
            // Concurrency guard: re-read the asset FOR UPDATE inside the
            // transaction and bail if it's already been scheduled. Two
            // concurrent callers (e.g. a double-click, or two recovery-command
            // workers) can both load the asset with a NULL
            // customised_calendar_entry_id; without this lock the second would
            // create a duplicate calendar entry + drafts and orphan the first.
            // The lock serialises them; the loser sees the winner's id and stops.
            $locked = BrandAsset::whereKey($asset->id)->lockForUpdate()->first();
            if ($locked && $locked->customised_calendar_entry_id) {
                throw new AlreadyScheduledException(
                    "Asset #{$asset->id} is already scheduled (calendar entry #{$locked->customised_calendar_entry_id})."
                );
            }

            $calendar = $this->customisedCalendar($brand);
            $entry = $this->createEntry($calendar, $brand, $asset, $platforms, $publishAt);

            $drafts = [];
            foreach ($platforms as $platform) {
                $drafts[] = $this->createDraft($brand, $entry, $asset, $assetUrl, $platform, $narrative, $hashtags);
            }

            // Stamp the asset with its customised-post provenance + reserve it
            // out of the general picker pool.
            $asset->forceFill([
                'usage_intent' => BrandAsset::INTENT_CUSTOMISED,
                'scheduled_platforms' => $platforms,
                'scheduled_post_for' => $publishAt,
                'narrative_source' => $narrativeSource,
                'customised_calendar_entry_id' => $entry->id,
            ])->save();

            app(SetupReadiness::class)->invalidate($brand);

            return ['calendar_entry' => $entry, 'drafts' => $drafts, 'asset' => $asset];
        });

        // Compliance runs AFTER the write transaction commits — it does LLM
        // (brand-voice) + pgvector (dedup) work that must not hold a write lock,
        // and a mid-LLM failure must not roll back the valid calendar/draft rows.
        // It mutates each draft's status in place (see runComplianceSafely).
        $this->runComplianceSafely($brand, $result['drafts']);

        return $result;
    }

    /**
     * Run the standard 7-check ComplianceAgent against each customised draft,
     * AFTER the scheduling transaction has committed. ComplianceAgent writes
     * the resulting status itself (compliance_failed / awaiting_approval /
     * approved, per the brand lane). We only handle the two non-pass exits:
     *
     *   - AgentPrerequisiteMissing (brand has no current brand_style): we can't
     *     score voice/grounding, so we park the draft at awaiting_approval for
     *     manual review rather than auto-publishing ungoverned copy.
     *   - any other error: same — leave it held, never silently auto-approve.
     *
     * In BOTH non-pass exits we ALSO record an explanatory ComplianceCheck row
     * (result='error') so the draft is not held with a blank Drafts page — the
     * operator sees a concrete reason for the hold (the agent never reaches its
     * own checkBrandVoice() error path because ensureReady() throws first, so
     * without this row there would be zero audit trail). Each draft is refreshed
     * so the returned models carry the TRUE post-compliance status (the caller's
     * notification reads it — otherwise it shows the stale 'compliance_pending').
     *
     * Per-draft try/catch so one platform's failure neither aborts the others
     * nor the upload request. Operator copy is never AI-rewritten: the
     * drafts:redraft-failed loop skips agent_role='operator' drafts.
     *
     * @param  array<int,Draft>  $drafts
     */
    private function runComplianceSafely(Brand $brand, array $drafts): void
    {
        foreach ($drafts as $draft) {
            try {
                app(\App\Agents\ComplianceAgent::class)->run($brand, ['draft_id' => $draft->id]);
            } catch (\App\Exceptions\AgentPrerequisiteMissing $e) {
                $this->recordComplianceHold(
                    $draft, $brand, 'prerequisite',
                    'Compliance could not run: the brand has no published voice/style yet ("'
                        . ($e->missingStage() ?? 'brand_style') . '"). Held for your review — finish the '
                        . 'brand setup and re-run compliance, then approve.',
                    ['missing_stage' => $e->missingStage()],
                );
                \Illuminate\Support\Facades\Log::info(
                    'CustomisedPostScheduler: compliance skipped (no brand_style) — held for review',
                    ['draft_id' => $draft->id, 'brand_id' => $brand->id, 'missing_stage' => $e->missingStage()],
                );
            } catch (\Throwable $e) {
                $this->recordComplianceHold(
                    $draft, $brand, 'compliance_error',
                    'Compliance check hit an unexpected error and could not complete. Held for your '
                        . 'review — re-run compliance, or approve if the copy is good.',
                    ['error' => substr($e->getMessage(), 0, 300)],
                );
                \Illuminate\Support\Facades\Log::error(
                    'CustomisedPostScheduler: compliance errored — held for review',
                    ['draft_id' => $draft->id, 'brand_id' => $brand->id, 'error' => substr($e->getMessage(), 0, 300)],
                );
            }

            // Refresh so the returned model reflects the status compliance set
            // (approved / awaiting_approval / compliance_failed) — the caller's
            // notification keys off this. Without it the model is the stale
            // 'compliance_pending' snapshot from createDraft().
            try {
                $draft->refresh();
            } catch (\Throwable) {
                // Row vanished mid-flight — nothing to refresh; leave as-is.
            }
        }
    }

    /**
     * Park a customised draft for manual review WITH an explanatory audit row,
     * so the Drafts page shows a concrete reason instead of a blank compliance
     * section. The status update is wrapped defensively: if it throws (infra
     * error / row deleted), we log and move on rather than letting it propagate
     * out of schedule() and surface to the operator as a generic failure while
     * leaving the draft stranded in 'compliance_pending' (invisible to every
     * downstream cron). The audit row is best-effort for the same reason.
     */
    private function recordComplianceHold(Draft $draft, Brand $brand, string $checkType, string $reason, array $details): void
    {
        try {
            \App\Models\ComplianceCheck::create([
                'draft_id' => $draft->id,
                'brand_id' => $brand->id,
                'check_type' => $checkType,
                'result' => 'error',
                'reason' => $reason,
                'details' => $details,
                'checked_at' => now(),
            ]);
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::warning(
                'CustomisedPostScheduler: could not record compliance-hold audit row',
                ['draft_id' => $draft->id, 'error' => substr($e->getMessage(), 0, 200)],
            );
        }

        try {
            $draft->update(['status' => 'awaiting_approval']);
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error(
                'CustomisedPostScheduler: could not park draft at awaiting_approval',
                ['draft_id' => $draft->id, 'error' => substr($e->getMessage(), 0, 200)],
            );
        }
    }

    /** One reusable "Customised posts" calendar per brand. */
    private function customisedCalendar(Brand $brand): ContentCalendar
    {
        return ContentCalendar::firstOrCreate(
            ['brand_id' => $brand->id, 'label' => 'Customised posts'],
            [
                'period_starts_on' => now()->startOfMonth()->toDateString(),
                'period_ends_on' => now()->addYear()->endOfMonth()->toDateString(),
                // pillar_mix + format_mix are NOT NULL (the Strategist agent fills
                // them for generated calendars). This reusable "Customised posts"
                // calendar is operator-driven and carries NO pillar/format strategy
                // — each post is authored directly — so we store empty mixes rather
                // than violate the constraint (SQLSTATE 23502). platform_mix is
                // nullable and left null. Casts serialise these to JSON.
                'pillar_mix' => [],
                'format_mix' => [],
                'status' => 'approved',
            ],
        );
    }

    private function createEntry(
        ContentCalendar $calendar,
        Brand $brand,
        BrandAsset $asset,
        array $platforms,
        Carbon $publishAt,
    ): CalendarEntry {
        // The asset's vision description anchors topic + visual_direction so any
        // later agent touchpoint (e.g. re-running Designer) stays on-subject.
        $topic = trim((string) ($asset->description ?: ($asset->original_filename ?: 'Customised post')));
        $visualDirection = $asset->description
            ? 'Use the operator-uploaded asset depicting: ' . $asset->description
            : 'Operator-uploaded brand asset.';

        // Store date in brand TZ; the auto-scheduler combines scheduled_date +
        // scheduled_time in the brand TZ and converts to UTC. We persist the
        // user's chosen instant interpreted in the brand timezone.
        $brandTz = $brand->timezone ?: 'UTC';
        $local = $publishAt->copy()->setTimezone($brandTz);

        return CalendarEntry::create([
            'content_calendar_id' => $calendar->id,
            'brand_id' => $brand->id,
            'scheduled_date' => $local->toDateString(),
            'scheduled_time' => $local->format('H:i:s'),
            'topic' => mb_substr($topic, 0, 255),
            'angle' => 'Operator-customised post',
            'pillar' => 'custom',
            'format' => $asset->isVideo() ? 'video' : 'single_image',
            'platforms' => $platforms,
            'objective' => 'operator_scheduled',
            'visual_direction' => mb_substr($visualDirection, 0, 1000),
            'is_pillar' => false,
            // calendar_entries.status is a CHECK-constrained enum:
            // ['planned','drafted','scheduled','published','skipped']. 'approved'
            // is NOT a member (that vocabulary belongs to content_calendars +
            // drafts) — using it 23514s the insert and rolls back schedule().
            // The operator pinned a date/time, so this entry is 'scheduled'
            // (the Strategist's autonomous entries enter at 'planned').
            'status' => 'scheduled',
        ]);
    }

    private function createDraft(
        Brand $brand,
        CalendarEntry $entry,
        BrandAsset $asset,
        string $assetUrl,
        string $platform,
        string $narrative,
        ?array $hashtags,
    ): Draft {
        // Respect the platform body cap (same source of truth the Writer uses).
        $cap = \App\Agents\Prompts\WriterPrompt::PLATFORM_LIMITS[$platform] ?? 1000;
        $body = mb_substr($narrative, 0, $cap);

        return Draft::create([
            'brand_id' => $brand->id,
            'calendar_entry_id' => $entry->id,
            'platform' => $platform,
            'content_type' => $asset->isVideo() ? 'video' : 'caption',
            'body' => $body,
            'hashtags' => is_array($hashtags) ? array_slice($hashtags, 0, 30) : [],
            'mentions' => [],
            // Asset pre-attached — bypasses DesignerAgent entirely.
            'asset_url' => $assetUrl,
            'asset_urls' => array_values(array_unique([$assetUrl, $asset->public_url])),
            // Provenance — this is an operator action, not an agent generation.
            'agent_role' => 'operator',
            // model_id is NOT NULL on drafts; no LLM wrote this body, so we
            // stamp the 'operator' sentinel (mirrors agent_role). Omitting it
            // 23502s the insert and rolls back the whole schedule() transaction.
            'model_id' => 'operator',
            'prompt_version' => 'customised-post.v1',
            'prompt_inputs' => [
                'brand_asset_id' => $asset->id,
                'narrative_source' => $asset->narrative_source ?? 'manual',
            ],
            'cost_usd' => 0,
            // Enter the compliance gate like any other draft. runComplianceSafely()
            // (called after this transaction commits) runs the 7 checks and sets
            // the landing status; the brand lane decides approved vs held. The
            // approval columns are intentionally NOT set here — they're stamped
            // when a human approves (amber/red) and stay null on green
            // auto-approve, matching the agent pipeline.
            'status' => 'compliance_pending',
            'lane' => $brand->defaultLaneFor($platform),
        ]);
    }

    /**
     * Lowercase, de-dupe, and drop anything not in SUPPORTED_PLATFORMS.
     * Public + static so it's the single source of truth for "which platforms
     * are valid for a customised post" and is unit-testable without the DB.
     *
     * @param  array<int,string>  $platforms
     * @return array<int,string>
     */
    public static function normalisePlatforms(array $platforms): array
    {
        return array_values(array_unique(array_filter(
            array_map(fn ($p) => strtolower(trim((string) $p)), $platforms),
            fn ($p) => in_array($p, self::SUPPORTED_PLATFORMS, true),
        )));
    }
}
