@extends('layouts.eiaaw')

@section('title', 'AI Content Disclaimer — EIAAW Social Media Team')
@section('description', 'How AI-generated content works in EIAAW Social Media Team, its limits, your review obligations, and where responsibility sits. Operated by EIAAW SOLUTIONS in Malaysia.')

@section('content')
<x-legal-shell
  eyebrow="Legal · AI Content"
  heading="AI Content <em>Disclaimer</em>"
  :updated="config('legal.documents.ai_disclaimer.updated')"
  intro="EIAAW Social Media Team uses artificial intelligence to draft captions, design images, and generate video. This disclaimer explains what that means, the limits of AI output, and your responsibilities. It forms part of, and is incorporated by reference into, our <a href='/terms'>Terms of Service</a>."
>
  <p class="meta">EIAAW SOLUTIONS · SSM Reg. No. 202603133419 (CT0164540-H) · Governed by the laws of Malaysia</p>

  <h2>1. You are interacting with AI</h2>
  <p>
    The captions, images, video, strategy recommendations, and compliance assessments produced by the service are generated by AI models, including third-party foundation models. We tell you this plainly, consistent with emerging AI-transparency expectations (including the EU AI Act's transparency obligations for synthetic and AI-assisted content).
  </p>

  <h2>2. AI output can be wrong</h2>
  <p>
    AI models can produce output that is inaccurate, outdated, biased, incomplete, or entirely fabricated (&ldquo;hallucinated&rdquo;), including invented facts, figures, citations, dates, prices, or claims. The Compliance gate and provenance receipts reduce risk but <strong>do not guarantee</strong> that any output is accurate, lawful, original, or fit for your purpose.
  </p>

  <h2>3. Human review is required</h2>
  <p>
    You must review AI-generated content before it is published. The service is designed around this: content on the Amber lane requires your explicit approval, and you remain in control of what goes live. By approving content for publishing you confirm you have reviewed it and accept responsibility for it.
  </p>

  <h2>4. You are the publisher and bear the risk</h2>
  <p>
    When you approve and publish content, <strong>you</strong> are the publisher of record. To the fullest extent permitted by Malaysian law, you assume all risk and liability arising from AI-generated content you publish &mdash; including any claim of inaccuracy, defamation, intellectual-property infringement, regulatory breach, or harm. We provide the tools; the editorial decision and its consequences are yours.
  </p>

  <h2>5. No warranty of originality or non-infringement</h2>
  <p>
    AI models are trained on large datasets. We do not warrant that any AI output is original, free of third-party rights, or non-infringing, and we make no representation about the provenance of model training data. You are responsible for confirming you have the rights to use, modify, and publish any output, and for clearing any third-party material (including brand assets, logos, music, and likenesses) you incorporate.
  </p>

  <h2>6. Synthetic-media labelling</h2>
  <p>
    Several platforms (including Meta, TikTok, and YouTube) require creators to disclose AI-generated or significantly AI-edited media. The service flags AI-generated media to help you comply, but the obligation to label and disclose your content correctly &mdash; on each platform and under any applicable law &mdash; rests with you as the publisher.
  </p>

  <h2>7. Provider dependence</h2>
  <p>
    AI generation depends on third-party providers (including Anthropic and FAL.AI). Their models, availability, and behaviour are outside our control and may change; an output you could generate yesterday may differ or be unavailable today.
  </p>

  <h2>8. Contact</h2>
  <p>
    Questions about how AI is used in the service can be sent to
    <a href="mailto:eiaawsolutions@gmail.com">eiaawsolutions@gmail.com</a>.
    See also our <a href="/terms">Terms of Service</a>, <a href="/acceptable-use">Acceptable Use Policy</a>, and <a href="/privacy">Privacy Policy</a>.
  </p>
</x-legal-shell>
@endsection
