<?php

namespace App\Mail;

use App\Models\User;
use App\Models\Workspace;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * One-shot welcome email sent right after Stripe Checkout success URL
 * provisions a new account. Carries the autogenerated temp password
 * because the user never picked one — they paid first, then the system
 * created the user.
 *
 * Mirrors Sales-marketing-agent's welcome email template:
 *   c:/laragon/www/Sales marketing agent/src/routes/billing.js (sendEmail call)
 */
class WelcomeWithCredentials extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    public function __construct(
        public User $user,
        public Workspace $workspace,
        public string $tempPassword,
        public string $loginUrl,
    ) {}

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Welcome to EIAAW Social Media Team — Your Login Details',
        );
    }

    public function content(): Content
    {
        $planConfig = config('billing.plans.'.$this->workspace->plan);

        return new Content(
            view: 'emails.welcome-with-credentials',
            with: [
                'user'         => $this->user,
                'workspace'    => $this->workspace,
                'tempPassword' => $this->tempPassword,
                'loginUrl'     => $this->loginUrl,
                'planName'     => $planConfig['name'] ?? ucfirst($this->workspace->plan),
                'trialDays'    => $planConfig['trial_days'] ?? 14,
                'trialEndsAt'  => $this->workspace->trial_ends_at,
                'forgotUrl'    => url('/agency/password-reset/request'),
            ],
        );
    }
}
