@php
    $severityColor = match ($event->severity) {
        'high' => '#B91C1C',
        'medium' => '#B45309',
        default => '#6B7A7F',
    };
    $severityLabel = strtoupper($event->severity);
    $occurredAt = optional($event->occurred_at)->format('Y-m-d H:i:s T');
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EIAAW security alert</title>
</head>
<body style="margin: 0; padding: 0; background: #FAF7F2; font-family: -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #0F1A1D;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background: #FAF7F2; padding: 40px 16px;">
    <tr>
      <td align="center">
        <table role="presentation" width="560" cellspacing="0" cellpadding="0" style="max-width: 560px; background: #FFFFFF; border: 1px solid #D9CFBC; border-radius: 16px; overflow: hidden;">
          <tr>
            <td style="padding: 32px 32px 0;">
              <div style="font-family: 'JetBrains Mono', SFMono-Regular, Menlo, monospace; font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: {{ $severityColor }};">
                EIAAW &middot; Security alert &middot; {{ $severityLabel }}
              </div>
              <h1 style="margin: 16px 0 0; font-size: 22px; font-weight: 600; letter-spacing: -0.02em; color: #0F1A1D; line-height: 1.3;">
                {{ $event->event_type }} &mdash; {{ $event->category ?? 'security' }}
              </h1>
              <p style="margin: 16px 0 0; font-size: 14px; line-height: 1.55; color: #2A3438;">
                The injection detector flagged an event at <strong>{{ $occurredAt }}</strong>.
                The LLM call was {{ $event->blocked ? 'BLOCKED' : 'allowed through (baseline mode — enforcement is off)' }}.
              </p>
            </td>
          </tr>

          <tr>
            <td style="padding: 24px 32px 0;">
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border: 1px solid #EDE3CF; border-radius: 12px; background: #FAF7F2;">
                <tr><td style="padding: 14px 16px; font-family: 'JetBrains Mono', SFMono-Regular, Menlo, monospace; font-size: 12px; color: #2A3438;">
                  <div><strong>severity</strong> &nbsp; {{ $severityLabel }}</div>
                  <div><strong>verdict</strong> &nbsp; {{ $event->verdict ?? '—' }}</div>
                  <div><strong>layer</strong> &nbsp; {{ $event->detector_layer ?? '—' }}</div>
                  <div><strong>confidence</strong> &nbsp; {{ $event->confidence !== null ? $event->confidence . '%' : '—' }}</div>
                  <div><strong>workspace</strong> &nbsp; {{ $event->workspace_id ?? '—' }}</div>
                  <div><strong>brand</strong> &nbsp; {{ $event->brand_id ?? '—' }}</div>
                  <div><strong>user</strong> &nbsp; {{ $event->user_id ?? '—' }}</div>
                  <div><strong>correlation_id</strong> &nbsp; {{ $event->correlation_id ?? '—' }}</div>
                </td></tr>
              </table>
            </td>
          </tr>

          @if ($event->evidence)
          <tr>
            <td style="padding: 16px 32px 0;">
              <p style="margin: 0 0 6px; font-family: 'JetBrains Mono', SFMono-Regular, Menlo, monospace; font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: #6B7A7F;">
                Evidence
              </p>
              <pre style="margin: 0; padding: 12px 14px; background: #0F1A1D; color: #FAF7F2; border-radius: 8px; font-family: 'JetBrains Mono', SFMono-Regular, Menlo, monospace; font-size: 12px; line-height: 1.45; white-space: pre-wrap; word-break: break-word;">{{ \Illuminate\Support\Str::limit($event->evidence, 600) }}</pre>
            </td>
          </tr>
          @endif

          @if ($suppressedCount > 0)
          <tr>
            <td style="padding: 16px 32px 0;">
              <p style="margin: 0; padding: 10px 14px; background: #FEF3C7; border: 1px solid #FDE68A; border-radius: 8px; font-size: 13px; color: #92400E;">
                <strong>{{ $suppressedCount }}</strong> additional event{{ $suppressedCount === 1 ? '' : 's' }} suppressed since the last alert (throttle bucket). Review the full ledger in the admin.
              </p>
            </td>
          </tr>
          @endif

          <tr>
            <td style="padding: 24px 32px 32px;">
              <a href="{{ $adminUrl }}" style="display: inline-block; padding: 11px 18px; background: #0F1A1D; color: #FAF7F2; text-decoration: none; border-radius: 999px; font-size: 13px; font-weight: 500; letter-spacing: 0.01em;">
                Open the admin
              </a>
              <p style="margin: 24px 0 0; font-size: 12px; line-height: 1.55; color: #6B7A7F;">
                This alert was generated by the prompt-injection detector and routed via Resend.
                The customer never saw the detector verdict &mdash; they got a generic error.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
